name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: fin-part-ord

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt -- --check
    - run: |
        rustup update
        rustup component add clippy
    - run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo build
    - run: env QUICKCHECK_GENERATOR_SIZE=32 cargo test
